osman = set('H')
osmanClon = frozenset('I')
osmanSuperClon = osman.union(osmanClon)
print(osmanSuperClon)
osmanSuperClon.add(2)
print(osmanSuperClon)
osmanSuperClon.add(5)
print(osmanSuperClon)
osmanSuperClon.remove(2)
osmanSuperClon.remove('I')
print(osmanSuperClon)
